### ISSUE TITLE
Control over alternates view links

### ISSUE THREAD

**Issue by rob-metalinkage** [surroundaustralia/VocPrez-theme-ogc#2]
another underlying VocPrez requirement ..  by default these use local links - but it should be possible to force some namespaces to resolve - this allows vocprez to be part of a larger set of options handled by a URI resolver - and is a must have for OGC application.

the best possible solution IMHO would be to take a set of know true/false for namespaces - and for unknown test the URIs and see if they support connegp - and cache the results in the true/false map.  This would be both easy to deploy and fully flexible in behaviour.

**Comment by nicholascar** [comment]
variable USE_ABS_ALT_URI (default False) overrides system URIs for the Alt Profiles links
