### ISSUE TITLE
check all top-level navigation options work

### ISSUE THREAD

**Issue by rob-metalinkage** [surroundaustralia/VocPrez-theme-ogc#3]
Ideally a regression testing for releases of vocprez and theme updates, not specific to this theme.
Things that must work:
1) home page collection view
2) Vocabularies list view
3) Search view
4) Concept scheme view page
5) Collection view page
6) Concept view page

**Comment by nicholascar** [comment]
> home page collection view

The links now work the same as other links in the system

> Vocabularies list view

List is now filterable

> Search view

Search now renders the correct links for Vocabs & Concepts

> Concept scheme view page

All Concept links work

> Collection view page

All good

> Concept view page

All good
