### ISSUE TITLE
Provide option to render additional properties

### ISSUE THREAD

**Issue by rob-metalinkage** [surroundaustralia/VocPrez-theme-ogc#4]
should be configurable to display additional properties

an "additional properties" section at the bottom of a concept page would be good. This could be based on a default (*), whitelist and/or blacklists.

having a property-path (shape) control could be used to whitelist as well as provide for extended display of object properties.

**Comment by nicholascar** [comment]
Commit https://github.com/RDFLib/VocPrez/commit/75bdfd8a9e8f344ca60f65e46880e5f0cd0e51c6 for VocPrez handles all properties by default that have a label (rdfs:label or dcterms:title) provided. Additionally, it knows about all SKOS, DCTERMS, DC, RDF & RDFS properties, so those don't need labels provided.

A list of suppressed properties is given in utils with currently these present:

* http://www.w3.org/2000/01/rdf-schema#label
* http://www.w3.org/2004/02/skos/core#inScheme
